services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:8.0
    container_name: mongodb8
    hostname: mongodb8
    restart: "on-failure" #unless-stopped #always
    volumes:
      - "mongodb_data:/data/db"
      - "mongodb_config:/data/configdb"
    ports:
      - "27017:27017"
    networks:
      - graylog_network
    
  opensearch:
    image: opensearchproject/opensearch:2.19.0
    container_name: opensearch
    hostname: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - "action.auto_create_index=false" 
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=+_8r#wliY3Pv5-HMIf4qzXImYzZf-M=M"
    ports:
      - "9200-9200" # "9203:9200"
      - "9300-9300" # "9303:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    networks:
      - graylog_network
    volumes:
      - "opensearch:/usr/share/opensearch/data"  

  graylog:
    image: graylog/graylog:6.3
    container_name: graylog6
    hostname: graylog6
    domainname: internal
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_PASSWORD_SECRET=0123456789ABCDEF
      - GRAYLOG_ROOT_PASSWORD_SHA2=1967bfa68e40013348762184193c2a457be7a6975d1d5da6a8161d0e9165dbbb
      - GRAYLOG_MONGO_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_REPORT_DISABLE_SANDBOX="true"
      - GRAYLOG_ELASTICSEARCH_HOSTS="http://opensearch:9200"
      - GRAYLOG_NODE_ID_FILE="/usr/share/graylog/data/config/node-id"
      - GRAYLOG_HTTP_BIND_ADDRESS="0.0.0.0:9000"
    restart: "on-failure"
    ports:
      - "9000:9000/tcp"     # Graylog web interface and REST API
      - "5044:5044/tcp"     # Graylog beats
      - "5140:5140/tcp" 	# Syslog TCP
      - "5140:5140/udp" 	# Syslog UDP 
      - "1514:1514" 		# Syslog
      - "1515:1515" 		# Syslog      
      - "12201:12201/tcp" 	# GELF TCP
      - "12201:12201/udp" 	# GELF UDP      
      - "13301:13301/tcp" 	# Forwarder data      
      - "13302:13302/tcp"   # Forwarder config
    depends_on: # service names
      mongodb:
        condition: service_started
      opensearch:
        condition: service_started
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh"
    networks:
      - graylog_network
    volumes:
      - "graylog_data:/usr/share/graylog/data/data" 

networks:
  graylog_network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config:
  opensearch:
  graylog_data:
    driver: local